### PR TITLE
CSV to JSON

### PR DESCRIPTION
**Pull request by shuba400**
__1__

#### Short description of what this resolves:
Converts selected rows of csv file to json format

#### Changes proposed in this pull request and/or Screenshots of changes:

- Deleted the duplicated movies.csv file
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Don't duplicate movies.csv file. Refer the same file which is given.

**Comment by shuba400** [comment]
Update- Linked the file with given one and deleted the duplicated copy

**Comment by Lokesh2703** [comment]
Change your description of PR follow the template write your issue number as \_\_ISSUENUMBER\_\_ not as #1  after that I will merge.

**Comment by shuba400** [comment]
Update- Changed PR template

**Comment by Lokesh2703** [comment]
> Change your description of PR follow the template write your issue number as __ISSUENUMBER__ not as #1 after that I will merge.

.

**Comment by shuba400** [comment]
OK understood the way of writing it

**Pull request merged**
