### PR TITLE
Task02 completed

### PR DESCRIPTION
**Pull request by ABans1**
__3__ 

 Short description of what this resolves:
Sorted all the files in their respective folders according to their extensions using os and shutil.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Don't submit changed folder.

**Comment by ABans1** [comment]
Sir what to do in response for now.

**Comment by ABans1** [comment]
My task2 folder is also there but I didn't know how to remove the task1 changed folder.

**Comment by Lokesh2703** [comment]
Clone the repo delete the changed folders, commit and push.

**Pull request closed without merging**
