### PR TITLE
Task #3 

### PR DESCRIPTION
**Pull request by PratyushPareek**
__3__ 

#3
#3

#### Short description of what this resolves:
Added the solution (python script) in submissions folder in my name's folder 
The python script sends a mail to my other ID directly

#### Changes proposed in this pull request and/or Screenshots of changes:
task3

-
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Dont write hardcoded passwords anywhere ask the user to give input

**Comment by PratyushPareek** [comment]
@Lokesh2703  Sir 'password' is very obviously not my real password and just an instruction for the user to replace it with his/her own password 
Same goes with the email ID

**Comment by Lokesh2703** [comment]
How can normal user know where to change in code so ask user to give input.

**Comment by PratyushPareek** [comment]
Done

**Comment by Lokesh2703** [comment]
Look at the issue number first and then create PRs now because of ur mistake u got only 10 points.

**Pull request merged**
