### PR TITLE
added

### PR DESCRIPTION
**Pull request by aarpit1010**
__3__ 

#### Short description of what this resolves:
Files can be organised according to their extensions.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Write some description in PR every time otherwise we can't review it.

**Comment by Lokesh2703** [comment]
Don't change any existing files during PR. Let others also do the task. Submit the script and if you are submitting changes submit them in your folder of Task_2

**Comment by aarpit1010** [comment]
Sir, How to edit my PR and add description ?

**Comment by Lokesh2703** [comment]
Use three dots:smile:

**Comment by aarpit1010** [comment]
Added description

**Comment by Lokesh2703** [comment]
> Don't change any existing files during PR. Let others also do the task. Submit the script and if you are submitting changes submit them in your folder of Task_2

.

**Comment by deepakDOTexe** [comment]
@aarpit1010 You have one more day to have this PR merged. After that I will close it due to no activity.

**Pull request closed without merging**
