### PR TITLE
TASK 3 done

### PR DESCRIPTION
**Pull request by Xenomorphing19**
__21__ 

 

#### Short description of what this resolves:
edited the script

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Xenomorphing19** [comment]
Sir,i was trying to push task 3 into master but i did the opposite
now this PR has both task 3 and task 4.
suggest something please

**Comment by Lokesh2703** [comment]
Add one more commit removing Task 4 in this PR

**Comment by orichamaru** [comment]
@Xenomorphing19 please follow above instruction and inform us by today

**Comment by Lokesh2703** [comment]
Closing this PR due to no response

**Pull request closed without merging**
