### PR TITLE
modified_as_getcwd()

### PR DESCRIPTION
**Pull request by infern018**
__3__

modified as getcwd()

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Have u closed ur previous PR on this same thing

**Comment by infern018** [comment]
Yes Sir I did closed my previous PR, please look through  my this PR

**Comment by Lokesh2703** [comment]
Your code is not working. Make sure you run the program before commiting. There is no os.path.getcwd() u have to use os.getcwd()

**Comment by orichamaru** [comment]
@infern018 can u add Screenshot

**Comment by infern018** [comment]
Screenshot (17)

**Comment by orichamaru** [comment]
@infern018 add Screenshot of organised folder 😅😅

**Comment by infern018** [comment]
Screenshot (18)
Sir Should i make a new PR with modified code and close this one?

**Comment by orichamaru** [comment]
@infern018 please don't modify original repo task2 folder. Don't organise files in task2 folder.

**Comment by infern018** [comment]
Ok Sir,. I'll correct that in next PR

**Pull request closed without merging**
