### PR TITLE
code for task_2

### PR DESCRIPTION
**Pull request by Abhijeet-sonkar**
__3__ 

#### Short description of what this resolves:
file organizer for different types of file

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Can u tell me how to run your code?

**Comment by Abhijeet-sonkar** [comment]
In the terminal go to the directory containing the folder(which needs to be organized)..say the folder name is "File"..
Then type  in the terminal .....

python  file_organizer.py  File

...this will organize the folder File

**Comment by Lokesh2703** [comment]
> In the terminal go to the directory containing the folder(which needs to be organized)..say the folder name is "File"..
> Then type in the terminal .....
> 
> python file_organizer.py File
> 
> ...this will organize the folder File

Absolute path or relative?

**Comment by orichamaru** [comment]
@Abhijeet-sonkar  there is no such file in your repo .Update it

**Comment by Abhijeet-sonkar** [comment]
actually in my repo  file_organizer.py is there.. ..
here is a screenshot...

Screenshot from 2020-01-18 19-48-13


not able understand what i did wrong

**Comment by orichamaru** [comment]
@Abhijeet-sonkar  Please provide me link of this script from your profile

**Comment by Abhijeet-sonkar** [comment]
https://github.com/Abhijeet-sonkar/Monty_Python_Class/blob/Abhijeet/Submissions/Abhijeet-sonkar/Task_2/file_organizer.py

**Comment by deepakDOTexe** [comment]
Make a new pull request

**Pull request closed without merging**
