### PR TITLE
csv2json

### PR DESCRIPTION
**Pull request by prince-7**
__1__ 

#### Short description of what this resolves:
This contains a python script to convert .csv file to .json file 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
Don't duplicate the given file refer the same file which is given to u.

**Comment by prince-7** [comment]
Changes have been made.

**Comment by Lokesh2703** [comment]
Format of output file is not correct. Look into it.

**Comment by prince-7** [comment]
corrected the .json file

**Comment by prince-7** [comment]
Corrected the pr

**Pull request merged**
