### PR TITLE
Task-2 solution

### PR DESCRIPTION
**Pull request by kavi-12**
__3__ 

#### Short description of what this resolves:

python script for organising the files based on their extensions

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by orichamaru** [comment]
@kavi-12  why are u opening 2 PRs of same TASK?

**Comment by kavi-12** [comment]
Sorry, the other one was a wrong pr.. I forgot to close it. This one is the correct one

**Comment by orichamaru** [comment]
@kavi-12  please  add screenshot of organised folder

**Comment by kavi-12** [comment]
IMG_20200120_132624__1579511282_171 76 180 63
IMG_20200120_132654__1579511336_171 76 180 63

**Comment by kavi-12** [comment]
screenshot of organised files

**Pull request merged**
