### PR TITLE
Task 1 completed

### PR DESCRIPTION
**Pull request by aawizard**
__1__ 

#### Changes proposed in this pull request and/or Screenshots of changes:

-https://prnt.sc/qrrwza
Screenshot of the movies file created and successful execution of the command on command line
-
-

### CODE REVIEW

**Comment by Lokesh2703** [comment]
> Traceback (most recent call last):
>   File "cvsTojson.py", line 5, in <module>
>     with open(csvFilePath,encoding = "utf8",errors = 'ignore') as csvFile:
> FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\Monty_Python_Class\\Task_1\\movies.csv'

I am getting this error use os.path.join() to join the path.

**Comment by Lokesh2703** [comment]
See if u r able to run the code and add screenshots here but don't submit changed files.

**Comment by aawizard** [comment]
https://prnt.sc/qrrwza    sir here is the screenshot of successful execution of the program

**Comment by deepakDOTexe** [comment]
Only movies having comdey as one of the genre should be in json file. 
Update your code

**Comment by aawizard** [comment]
sir, please view the pr again

**Comment by Lokesh2703** [comment]
Also let monty know what other genres are for a particular movie other than comedy in that json file.
Dont make genres of those which has comedy as one of the genres to only comedy genre,

**Pull request merged**
